services:
  db:
    image: postgres:15-alpine
    container_name: template-fullstack_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB_NAME:-template-fullstack}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    container_name: template-fullstack_nats
    ports:
      - "4222:4222" # Client Port
      - "8222:8222" # HTTP Management/Monitoring Port
    # Optional: Enable JetStream for message persistence
    command: [ "-js" ]

volumes:
  postgres_data:
